### ISSUE TITLE
i3 freezes because of this gem

### ISSUE THREAD

**Issue by thisredone** [veelenga/i3ipc-ruby#5]
I was running a simple script to notify me of new messages from messenger.com. As it turned out it was causing frequent unrecoverable freezes of i3 due to some misuse of the IPC.
##### related i3 issues:

https://github.com/i3/i3/issues/2309
https://github.com/i3/i3/issues/1876
##### my script:

``` ruby
    require 'i3ipc'

    i3 = I3Ipc::Connection.new

    def write(val)
      File.write '/tmp/messenger_res', val
    end

    write ''

    th = i3.subscribe 'window', (Proc.new do |r|
      props = r.container.window_properties
      if r.change == 'title' && props.instance == 'www.messenger.com'
        write(props.title == 'Messenger' ? '' : props.title)
      end
    end)

    trap('SIGINT') { th.kill; th.join; exit }

    loop { sleep 1 }
```

**Comment by veelenga** [comment]
@thisredone I do not have much time right now for this project, but will try to look into this problem asap. 

@karkhaz you've been involved into subscription mechanism development, any ideas ?

**Comment by veelenga** [comment]
Closing because this is a stale issue.
